openapi: 3.1.0
info:
  title: Cow Service
  description: |-
    Workflow API
  version: 1.0.0
paths:
  /cow/{id}:
    get:
      operationId: getCow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: got the cow
          content:
            application/json:
              schema:
                type: object
                properties:
                  color:
                    description: color of cow
                    type: string
                  numberHorns:
                    description: number of horns on cow
                    type: number
  /cow:
    post:
      operationId: createCow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                color:
                  description: color of cow
                  type: string
                numberHorns:
                  description: number of horns on cow
                  type: number
      responses:
        200:
          description: Create a cow
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: id of the created cow
                    type: number
                  color:
                    description: color of cow
                    type: string
                  numberHorns:
                    description: number of horns on cow
                    type: number
