openapi: 3.1.0
info:
  title: Oven Service
  description: |-
    Workflow API
  version: 1.0.0
paths:
  /oven/{id}:
    get:
      operationId: getOven
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: got the oven
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    description: oven temperature
                    type: number
                  aroma:
                    description: aroma while oven is hot
                    type: object
                    properties:
                      aromaLevel:
                        description: oven aroma level while hot
                        type: number
